#!/bin/sh

echo "cclean : 42 Mac session cleaner"
echo "clean : 42 Linux session cleaner"
echo "ccp : c++ -Wall -Wextra -Werror -std=c++98"
echo "codeui: create code ui settings.json"
echo "code : Mac: open vscode"
echo "vsc : Linux: open vscode"
echo "fillc : fill .cpp files into Makefile"
echo "fillh : fill .hpp files into Makefile"
echo "cppm : create cpp Makefile"
echo "cm : create c Makefile"
echo "ocf : orthodox canonical form"
echo "main : create cpp main file"
echo "header : create hpp header file"
echo "usage : disk usage"
